// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace iTheatre.Views
{
	public partial class MoviesViewController : NSViewController
	{
		public MoviesViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
